steps:
  # initialise NPM config
  - name: bash
    id: checkout
    entrypoint: sh
    args:
      - '-c'
      - |
        ls -la
  # pull lfs files 
  - name: jgpelaez/git-lfs:latest
    id: git-lfs-pull
    entrypoint: sh
    args:
      - '-c'
      - |
         ls -la
         git lfs pull
         du -h TestLarge.pptx